### PR TITLE
better windows support

### PR DESCRIPTION
**Pull request by vitalych**
Signed-off-by: Vitaly Chipounov <vitaly@cyberhaven.io>

### CODE REVIEW

**Comment by adrianherrera** [comment]
Why are we putting binaries under version control? Can't we make it a "release"? https://help.github.com/articles/creating-releases/

**Review by adrianherrera — DISMISSED** [review]

**Comment by adrianherrera** [comment]
Can you please check that you can rebuild s2e.sln from scratch? I was just mucking around with it and it wouldn't build until I made the following change in `windows/drvctl/drvctl.vcxproj`:

```
<IncludePath>$(SolutionDir)/driver;...
```

to

```
<IncludePath>$(SolutionDir)/driver/include;...
```

**Comment by vitalych** [comment]
works for me, but there is indeed a problem in the vcxproj:
$(SolutionDir)/driver;$(SolutionDir)/libcommon/include;$(IncludePath);$(SolutionDir)/driver/include
The first include is wrong, the last one is correct

**Comment by adrianherrera** [comment]
Ok, interesting. I didn't notice that last include path because I just thought there was a mistake in the first one. Well, if it's working let's just go with it.

**Review by adrianherrera — APPROVED** [review]

**Pull request merged**
